### ISSUE TITLE
Clean-up bittorrent bootstrap.dat.old

### ISSUE THREAD

**Issue by kylemanna** [kylemanna/docker-bitcoind#10]
Need to determine a simple way to clean-up `bootstrap.dat.old` without other simultaneous running processes in the container (cron, init, process manager, etc).

One thought is to leverage `btc_oneshot` to check for the file, and delete it if it's older then say, 14 days.  This would happen automatically by the upstart.init file on reboot/restart and is probably what the user wants.

If the file is less than 14 days old, it's nice to keep it around so that it could be relocated and used for seeding as mentioned in issue #9.

Long term a solution is needed to determine how to expire the torrent file when new torrent files are created and old ones are abandoned.  First thought is to store metadata about the torrent file in the Docker image and then the Docker image as it will be periodically updated.

**Comment by hectorj** [comment]
The torrent bootstrap method is now obsolete : https://bitcointalk.org/index.php?topic=145386.0

> IMPORTANT NOTE:  As of Bitcoin Core version 0.10.0 or later, this torrent is slower than a direct download using the bitcoin P2P protocol & client.  This torrent is now only maintained for research and development purposes as a secondary option.  Please use Bitcoin Core directly to download the blockchain.

**Comment by kylemanna** [comment]
What's the move here, rip out all the torrent stuff?

I'd be curious to see a benchmark if anyone has one handy.  Running new docker bitcoind instances to test out timing would be pretty trivial.

**Comment by Levino** [comment]
I agree with @hectorj No bootstrap whatsoever.
