### ISSUE TITLE
Create systemd service file

### ISSUE THREAD

**Issue by kylemanna** [kylemanna/docker-bitcoind#13]
Need to create a systemd service file that does the same as the `upstart.init` file.  Service file is easy, testing is hard because it's time consuming.

**Comment by Levino** [comment]
Why?

**Comment by kylemanna** [comment]
To manage the docker containers that die or need to be started at boot.  Just like the upstart.init file.  The docker restart policy isn't really a good solution for this, and doing it manually is even worse.  Assuming your hosts and services never crash is a bit naive too.

**Comment by Levino** [comment]
I use the docker restart solution and am pretty good with it. Wouldn't like the container itself to manage it.

**Comment by kylemanna** [comment]
Ironically, the container managing itself is closer to the restart policy then a sane system process manager on the host (not in the container) managing the container.

More details @ https://docs.docker.com/articles/host_integration/#using-a-process-manager

Also, nobody needs to use the upstart or systemd service.  They are provided as conveniences external to the Docker image.  Haven't had time to test the systemd service yet though.
