### ISSUE TITLE
Set bitcoind params via env variables

### ISSUE THREAD

**Issue by Levino** [kylemanna/docker-bitcoind#15]
How about respecting environment variables like

```docker run bitcoind -e RPC-PASSWORD:xxx```

If you agree on usefulness I might write a pr.

**Comment by kylemanna** [comment]
Today you could run:

    docker run kylemanna/bitcoind -rpcpassword=asdf

I don't think the ENV variable adds value over that, and I prefer less code.  Occam's razor.

In my opinion the best approach is to extract the psuedo-random generated password:

    docker run --rm --volumes-from=bitcoind-data busybox cat /bitcoin/.bitcoin/bitcoin.conf

**Comment by kylemanna** [comment]
Please let me know if you think I missed something!

**Comment by kelostrada** [comment]
I didn't read this one before, but I guess it's resolved by https://github.com/kylemanna/docker-bitcoind/pull/23 anyway even though before you considered this not really required :) I think you can close this issue, but probably we would want some docs about the env variables available. Maybe I'll create some PR later with this too

**Comment by kylemanna** [comment]
It's because #23 came with a pull request.
