### ISSUE TITLE
bitcoin-cli and `error: couldn't connect to server`

### ISSUE THREAD

**Issue by 1905** [kylemanna/docker-bitcoind#18]
After doing "quick start" I waited for a few days. CPU was 100% and 41gb of data was downloaded.

Buy I still can't connect with bitcoin-cli.

**docker run --volumes-from=bitcoind-data --rm -it kylemanna/bitcoind bitcoin-cli getinfo**

gives me *error: couldn't connect to server*
Usually I get whit when blockchain was not fully loaded.

Right now CPU load is 1-2%

**docker logs -f bitcoind-node**

showing some old blocks
`4cbedb5749b972cf1191508a43fb7f06f789a71b70709cc  height=25194  log2_work=46.620872  tx=25355  date=2009-10-18 00:08:20 progress=0.000132  cache=6.0MiB(23623tx)
UpdateTip: new best=00000000fef8903bda5d6bcc6ff1c396b93730c425ee637e14f9d98eea6ac086  height=25195  log2_work=46.620929  tx=25356  date=2009-10-18 00:19:24 progress=0.000132  cache=6.0MiB(23624tx)
UpdateTip: new best=000000006f9cd96b8bec9b08d4891bb9d0d3723a3967e19e4943e498dec99784  height=25196  log2_work=46.620986  tx=25357  date=2009-10-18 00:58:37 progress=0.000132  cache=6.0MiB(23625tx)
UpdateTip: new best=00000000b0f920c91fd933436084ec4eea4072210d2d80cea71090e211baa081  height=25197  log2_work=46.621044  tx=25358  date=2009-10-18 01:00:40 progress=0.000132  cache=6.0MiB(23626tx)
UpdateTip: new best=00000000e3fb23aa147bf48c22cdb1e2fc2b00522be508e89e9ec6f364a78f0e  height=25198  log2_work=46.621101  tx=25359  date=2009-10-18 01:12:44 progress=0.000132  cache=6.0MiB(23627tx)`

System: Debian
`3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`
Hosted on Digital Ocean plan ($ 40 / mo)
Docker version 1.8.1, build d12ea79

Can somebody explain what happening?
Do I need to wait more?

**Comment by kylemanna** [comment]
When you run the get info command, you're running it in another container that can't communicate with the running process.

Instead, try running the get info command in the existing container (guessing from memory):

    docker run exec -it <container hash> bitcoin-cli getinfo

The longer term solution is to port forward the control port as described in the README with `-p 127.0.0.1:8332:8332`.

**Comment by 1905** [comment]
Thank you so much! I'm new to docker, my fault.
Going to learn it more.

**Comment by kylemanna** [comment]
No worries, glad to hear you got it working. :)

If the documentation is lacking, feel free to send a pull request.
