### ISSUE TITLE
Add ability to bootstrap from BitTorrent

### ISSUE THREAD

**Issue by kylemanna** [kylemanna/docker-bitcoind#2]
Add the ability to bootstrap the bitcoind-data volume using the BitTorrent network.  The BitTorrent is much better suited to distributed 20GB+ of block chain data.

Initial concern is that downloading the bootstrap data feeding it to bitcoind will exceed the 30GB partition size on the cheap VPS (read: DigitalOcean 30 GB droplet).

Details: https://bitcointalk.org/index.php?topic=145386.0

**Comment by hectorj** [comment]
It is possible to feed it an already downloaded bootstrap.dat with a command like that to start the daemon (after running the init) :

`$ docker run --volumes-from=bitcoind-data --name=bitcoind-node -d -p 8333:8333 -v /path/to/your/bootstrap/directory:/btcbootstrap kylemanna/bitcoind bitcoind -disablewallet -loadblock=/btcbootstrap/bootstrap.dat`

**Comment by hectorj** [comment]
I am also working on giving the option to make the init command download the torrent here : https://github.com/hectorj/docker-bitcoind/tree/torrent-bootstrap

But it's not finished (need to parametrize it, and probably detect and delete bootstrap.dat.old to save some space) and not tested yet (I do not have admin access to my router right here right now, and aria2 doesn't support UPnP)

**Comment by kylemanna** [comment]
@hectorj glad to see you're working on this!

Few comments:
1. I'm not sure that GPG verification is necessary since the bitcoin client will verify the bootstrap data when it imports it.  See "[Why should I trust you?](https://bitcointalk.org/index.php?topic=145386.msg1542831#msg1542831)".  Stripping the GPG verification step would greatly simplify the script at the risk that an adversary compromises jgarzik's server and a bad magnet URL is fetched.
2. Cron isn't (and shouldn't be) running in this container, so your work with cron probably isn't working.

Other then that keep goin' with it! I had never heard of aria2 before, it definitely looks lighter weight then my goto bittorrent cli client, transmission.

**Comment by kylemanna** [comment]
I started updating a few things with the project which then spiraled out of control to a bunch of things I had on backlog... which should make it easier to add bootstrap support.

The wrapper script is gone and the expectation is that there will be simple scripts under `bin` to do tasks (i.e. `bin/btc_init`).  I'd create a `btc_bootstrap` script that does your necessary task and then write up how to use it in a markdown file under the `docs` directory.

**Comment by hectorj** [comment]
It's true the GPG check is not mandatory, but it's not a big problem (I got that working already)

About the cron, I'll try something with inotify instead

About aria2, I am still having some troubles during my tests : it gets "aborted" near the end. I don't know if it's related directly to aria2, docker, or my VPS. I have some research to do on that

**Comment by hectorj** [comment]
Docker works like hell on my VPS (tons of errors like "Unknown filesystem type", or "Input/Output error") so my progress is stalled for now...

**Comment by kylemanna** [comment]
I've seen those errors before on some other VPS providers (prometeus.net comes to mind) that I've tried.  I blame their kernel not having good aufs/dm/btrfs support.  I'd suggest another provider if you can.  What virtualization technology does the provider use?

I just managed to use `aria2c http://gtf.org/garzik/bitcoin/bootstrap.dat.torrent` just fine on a Digital Ocean droplet I have for testing.  Unfortunately, DO is awfully expensive to run a full node.

**Comment by hectorj** [comment]
I am using a VPS from https://www.bitronictech.net/ubuntu-vps-hosting.php, they use Xen. I'll contact their support.

I did manage to download the bootstrap via my docker container, but I'd like to do more tests before calling it stable.

**Comment by hectorj** [comment]
Note in case someones else with the same problems read this : Fixed my issue, it was indeed a problem with the kernel version. I thought I updated it, but GRUB was still booting on the old one.
