### ISSUE TITLE
is it possible to run this in conjunction with a local test net? 

### ISSUE THREAD

**Issue by s-matthew-english** [kylemanna/docker-bitcoind#25]
I have a local test net that I've created using this: 

https://github.com/freewil/bitcoin-testnet-box

having just created some toy example blocks and transactions, can I somehow prescribe that my local testnet is the one used?

**Comment by kylemanna** [comment]
The docker command line arguments are passed to the bitcoind binary.  Should be something similar to `docker run ... kylemanna/bitcoind -testnet`

**Comment by s-matthew-english** [comment]
yeah but- isn't that for the global "testnet" i.e. the *official* one- I just want to run it on my own personal local testnet

**Comment by kylemanna** [comment]
It certainly is possible.  YOu'll have to do the work to bitcoind itself.  At the end of the day this docker container just wraps and simplifies the use of the bitcoind binary.

**Comment by MaxCCC** [comment]
@kylemanna @s-matthew-english  Can I do the following?
So usemy own `bitcoin.conf` and try to connect to testnet? (I always thought I would need `18333`)
```
 docker run -v bitcoind-data:/bitcoin --name=bitcoind-node -d \
        -p 8333:8333 \
        -p 127.0.0.1:8332:8332 \
        -v /etc/mybitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf \
        kylemanna/bitcoind -testnet

```
