### ISSUE TITLE
how much space does it actually gonna take?

### ISSUE THREAD

**Issue by boistordu** [kylemanna/docker-bitcoind#35]
Hi, 

it appears that it has taken already much more than 40GB for my volume and I just created yesterday... any ideas about how much it will take?

**Comment by hypergig** [comment]
86 gigs as of one week ago

**Comment by kylemanna** [comment]
Yeah, it keeps growing, mine is about 90GB.  Sorry to mislead. I have updated the README.

As for being more space efficient, consider the [`bitcoind -prune` option](https://en.bitcoin.it/wiki/Running_Bitcoin).

**Comment by boistordu** [comment]
is it more or less accurate or this is not related?  
https://blockchain.info/charts/blocks-size

**Comment by kylemanna** [comment]
> is it more or less accurate or this is not related?
> https://blockchain.info/charts/blocks-size

It's close.

Says the block size was about 81GB on Aug 28.

As of now my `.bitcoin` directory is 88GB with 87GB under `.bitcoin/blocks`

**Comment by boistordu** [comment]
thanks for all this precision. My doesn't seems to work it doesn't seem to calculate anything. but that s another issue post if you are able to look at it :)
