### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by willgdjones** [kylemanna/docker-bitcoind#44]
With the installation commands, I receive an out of disk space error. However, I have plenty of disk space on my system. Attempting to restart the download of the blockchain results in an error.

When specifying that I would like to reserve 200g in the volume with:

`docker volume create --opt o=size=200g --name=bitcoind-data`

and then attempted to start the container using the volume:

`docker run --volume bitcoind-data:/bitcoin --volume-driver local --name=bitcoind-node -d -p 8333:8333 -p 127.0.0.1:8332:8332 kylemanna/bitcoind`

results in the error:

`docker: Error response from daemon: missing device in volume options.`

**Comment by samob** [comment]
I have noticed high memory consumption of this image. Running on RancherOS 1.1.3 baremetal server that looks like this:
![kubernetes-stats](https://user-images.githubusercontent.com/335163/34913391-f94f93c2-f8fb-11e7-81b3-66ab0f28e29e.png)

When I first looked at deployed image, the memory consumption stated around 2Gb, but tended to grow at slow pace. In morning next day, I found container in inresponsive state. Had to forcefully stop/start it. Now it stopped to grow at 7.69Gb
![bitcoind-statsw](https://user-images.githubusercontent.com/335163/34913419-178f9138-f8fd-11e7-9adc-459f7b352db1.png)

Regarding diskspace I have not noticed any problems:
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         130G   78G   46G  64% /
tmpfs           7.9G     0  7.9G   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda1       130G   78G   46G  64% /bitcoin
shm              64M     0   64M   0% /dev/shm
tmpfs           7.9G     0  7.9G   0% /sys/firmware
```
 
I'm new to Docker world and I have seen the options to put cap limits to containers, I just wanted to see what resources are used during the life of this container. So the question that bugs me is that expected/usual memory consumption?

**Comment by dlednik** [comment]
@samob Did you try using security/host section of your container:

![image](https://user-images.githubusercontent.com/5610466/36159457-a7105c5c-10d6-11e8-917b-2c393e44d7f6.png)
