### ISSUE TITLE
run btcoind on testnet

### ISSUE THREAD

**Issue by MaxCCC** [kylemanna/docker-bitcoind#45]
Is it possible to connect with testnet with this image?
Or do we need `18333` etc?

`docker run -v bitcoind-data:/bitcoin --name=bitcoind-node -d      -p 8333:8333      -p 127.0.0.1:8332:8332      kylemanna/bitcoind -testnet`

```
bitcoin-cli getinfo
{
  "version": 140200,
  "protocolversion": 70015,
  "blocks": 32,
  "timeoffset": 0,
  "connections": 3,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```

When I try:
```
 docker run -v bitcoind-data:/bitcoin --name=bitcoind-node -d \
     -p 18333:18333 \
     -p 127.0.0.1:18332:18332 \
     kylemanna/bitcoind -testnet

```
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
```
```

**Comment by dimorinny** [comment]
Can you please explain, how did you fix this problem?

**Comment by chriscohoat** [comment]
@dimorinny to run on the testnet you can run the following command:

```
docker run -v bitcoind-data:/bitcoin -it -p 18333:18333 \
     -p 127.0.0.1:18332:18332 \
     kylemanna/bitcoind btc_oneshot -testnet=1 -rpcallowip=::/0
```
