### ISSUE TITLE
Update to bitcoin-core-0.15.0.1

### ISSUE THREAD

**Issue by christianboyle** [kylemanna/docker-bitcoind#46]
Hi Kyle, great resource here tyvm for releasing it! 

Any chance of a new build using core 0.15.0.1?

**Comment by kylemanna** [comment]
Just kicked off a rebuild with v0.15.0.0, looks like v0.15.0.1 hasn't been packaged just yet.

**Comment by christianboyle** [comment]
Perfect, thanks Kyle!

**Comment by kylemanna** [comment]
Thanks for keeping an eye on it.  Feel free to ping me when new releases hit the upstream Ubuntu repos and I can kick off new builds.

**Comment by christianboyle** [comment]
No sweat, sounds good.
