### ISSUE TITLE
traffic limit

### ISSUE THREAD

**Issue by dlednik** [kylemanna/docker-bitcoind#49]
is there a way to limit upload traffic on this image? 

If not where could I modify the config for that?

**Comment by cuzic4n** [comment]
https://jlopp.github.io/bitcoin-core-config-generator/
See Max Upload Target
Tries to keep outbound traffic under the given target (in MiB per 24h), 0 = no limit.
Take that and update your bitcoin.conf file under bitcoind-data/.bitcoin/bitcoin.conf

**Comment by dlednik** [comment]
will try that 👍
