### ISSUE TITLE
Skip the bootstrap if the file is already downloaded and has valid checksum

### ISSUE THREAD

**Issue by phuongnd08** [kylemanna/docker-bitcoind#5]
Could btc_bootstrap exit if the bootstrap is already downloaded and has valid checksum?

**Comment by hectorj** [comment]
It seems just adding this option could do the trick : http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-V

I'm gonna test it, brb

**Comment by phuongnd08** [comment]
My recent thought is it's better to check if the .bitcoin/blocks folder is already created. This indicate that the bitcoind has been running before and thus can be used to assume that we no longer need the bootstrap file, given we run the bitcoind as soon as bootstrap finishes download

**Comment by hectorj** [comment]
That's a good idea.

We'd need a "--force" option in case we want to bypass the check (I can see two cases : btcd started by mistake or too slow, so the user stops it and now wants to download the bootstrap)

We can also check for the existence of bootstrap.dat.old

Anyway, the "check-integrity" is still a good option to add to the torrent download
