### ISSUE TITLE
Couldn't connect with rpc

### ISSUE THREAD

**Issue by baambaam** [kylemanna/docker-bitcoind#58]
used commands:
`docker volume create --name=bitcoind-data`
`docker run -v bitcoind-data:/bitcoin --name=bitcoind-node -d -p 8333:8333 -p 127.0.0.1:8332:8332 kylemanna/bitcoind`
bitcoin-cli works fine:
`docker exec -it bitcoind-node bitcoin-cli getblockchaininfo`
but curl couldn't get response:

> λ curl -v localhost:8332
> * Rebuilt URL to: localhost:8332/
> *   Trying ::1...
> *   Trying 127.0.0.1...
> * connect to ::1 port 8332 failed: Connection refused
> * connect to 127.0.0.1 port 8332 failed: Connection refused
> * Failed to connect to localhost port 8332: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to localhost port 8332: Connection refused

this is the same
`curl -v -u bitcoinrpc:PWgnaXeUDG3PBpr/6uE/ZuKMO7/pkgAQqGBY8bqYhmxj http://127.0.0.1:8332`

any ideas why?

**Comment by mrbianchi** [comment]
I'm having issues too, but testnet 18332. On logs:
> Binding RPC on address :: port 18332 failed.
I tried with multiple ports, testnet or not testnet, but the result is the same
My OS Ubuntu 18

**Comment by cogutvalera** [comment]
I've the same issue, why it is closed ? Is it fixed already ? How to fix it ?

**Comment by BarrowHill** [comment]
I have the same issue on bitcoind from version 19.1
Failed to connect to 127.0.0.1 port 8332: Connection refused
with version 15.0 all works fine. How to solve this issue??

**Comment by mrbianchi** [comment]
i fixed it, you have to enter to config bitcoind to listen all interfaces, because when you rpc , the incoming traffic in bitcoind doesnt come from 127.0.0.1 , it comes from docker network
