### ISSUE TITLE
Wrong USER_ID / GROUP_ID and permissions on volume

### ISSUE THREAD

**Issue by d-rez** [kylemanna/docker-bitcoind#59]
-- Synology Docker

For whatever reason after creating / launching the container user bitcoin is always 1000:1000 instead of what I've specified in environment.

I can confirm that ENV variables are being passed to the shell. It's messing up permissions on my host OS. Other images using ENV variables switch the UID/GID correctly.

Is there a way to work around this?

```
root@kylemanna-bitcoind1:~# echo $USER_ID                                                                              
1034                                                                                                                   
root@kylemanna-bitcoind1:~# echo $GROUP_ID                                                                             
65537                                                                                                                  
root@kylemanna-bitcoind1:~# grep bitcoin /etc/passwd /etc/group                                                        
/etc/passwd:bitcoin:x:1000:1000::/bitcoin:/bin/bash                                                                    
/etc/group:bitcoin:x:1000:
```

**Comment by d-rez** [comment]
I was able to work around this by mounting modified `/etc/passwd` and `/etc/group` with correct UID/GIDs.

Not perfect but works

**Comment by kylemanna** [comment]
Can you try with `docker run ... -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro ...`?

This is more of a docker problem with inconsistent IDs between host filesystem and container. Not sure of how to fix the mapping "correctly".

**Comment by d-rez** [comment]
Yup that's exactly what I've been doing since last year :) Thanks anyway!
