### ISSUE TITLE
Version 0.18.0 available, rebuild please

### ISSUE THREAD

**Issue by 1n5aN1aC** [kylemanna/docker-bitcoind#60]
Version 0.18.0 is available on ~7 weeks now:
https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin

Could you launch an image build on the docker store ?

Thanks.

**Comment by kylemanna** [comment]
Bumped, should be good now.  Thanks for pointing this out:

    ~ ❯❯❯ docker run --rm -it kylemanna/bitcoind:latest  bitcoind --version
    Bitcoin Core Daemon version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65
    Copyright (C) 2009-2019 The Bitcoin Core developers
 
    Please contribute if you find Bitcoin Core useful. Visit
    <https://bitcoincore.org> for further information about the software.
    The source code is available from <https://github.com/bitcoin/bitcoin>.
 
    This is experimental software.
    Distributed under the MIT software license, see the accompanying file COPYING
    or <https://opensource.org/licenses/MIT>
 
    This product includes software developed by the OpenSSL Project for use in the
    OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
    Eric Young and UPnP software written by Thomas Bernard.

**Comment by 1n5aN1aC** [comment]
...Of course now my electrum server can no longer connect to it, but I'm pretty sure that's not your fault.

Thanks!

**Comment by 1n5aN1aC** [comment]
As a comment, it wasn't an Electrum issue, it was something with the bitcoind docker.

RPC was failing to bind to the port in bitcoind docker.

I worked around this by providing the following in my config file.
```
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
```
NOTE:  I run both dockers in their own docker network, and the RPC port is not forwarded outside of that network at all.

**Comment by kylemanna** [comment]
Wasn't aware of this, but it is mentioned the change notes: https://bitcoin.org/en/release/v0.18.0#configuration-option-changes

Can also invoke with `docker run --rm kylemanna/bitcoind --rpcbind=0.0.0.0`
