### ISSUE TITLE
Couldn't connect with rpc

### ISSUE THREAD

**Issue by BarrowHill** [kylemanna/docker-bitcoind#64]
Failed to connect to 127.0.0.1 port 8332: Connection refused
this happened when I update bitcoin core from version 15.0 to 19.1.
With 15.0 all was working fine, what is the difference in RPC methods in bitcoind from 19.1 ???

**Comment by chiguireitor** [comment]
Getting this on the latest 0.21 update too

**Comment by kylemanna** [comment]
Looks like I had a bug, see PR #72 for details.

Sorry. Need more CI tests to catch these issues, but unfortunately building and testing bitcoind has historically flagged my account as abusive for assuming it's minig bitcoins on Travis-CI. 🙄 

Please let me know if this does or doesn't work.

Thanks!

**Comment by chiguireitor** [comment]
Awesome, maybe having versioned releases on docker hub could alleviate some of these issues? too many times i've had the `down --rmi=all` dance with your awesome image and then proceed to several hours of debugging to discover a botched new version XD

**Comment by kylemanna** [comment]
Well written tests that run Github Actions that build the container and test against is is always welcome.  Some simple tests could be to make sure the client can connect to the daemon.
