### ISSUE TITLE
bitcoin-cli getnewaddress 

### ISSUE THREAD

**Issue by leoa12412a** [kylemanna/docker-bitcoind#65]
Sorry , my english is not very well , buy i has a problem hope you can help me
I user command bitcoin-cli getnewaddress  and bitcoin-cli getblance
return:
error code: -32601
error message:
Method not found

i remark the disablewallet=1 and "docker exec {CONTAINER ID} bitcoind -conf=/bitcoin/.bitcoin/bitcoin.conf -rescan"
but it still the same, is it still disable wallet?
what can I do ? what command can show wallet status ? can you help me

**Comment by kylemanna** [comment]
This docker container really isn't intended to manage a wallet. It's too likely that people will lose their wallet as a result of not understanding docker volumes.  I'd recommend running the client natively on your host for wallet operations.

**Comment by SablyTv** [comment]
> This docker container really isn't intended to manage a wallet. It's too likely that people will lose their wallet as a result of not understanding docker volumes. I'd recommend running the client natively on your host for wallet operations.

But for those who do understand it? Im running this on my truenas server as its easy setup. Making my own little thing and need to make addresses/wallets. You got any references to a different docker image that allows this?
