### ISSUE TITLE
Version 0.20.1 available

### ISSUE THREAD

**Issue by pricejn2** [kylemanna/docker-bitcoind#66]
0.20.1 was released in August https://bitcoincore.org/en/2020/08/01/release-0.20.1/ but it looks like this docker image is still running 0.18.0

Thanks!

**Comment by kylemanna** [comment]
Can you test #67 and I can merge it?

**Comment by pricejn2** [comment]
Thank you for pre-emptively merging this. I can confirm it this image is now using bitcoind v0.20.1.
