### ISSUE TITLE
Where is data stored?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [kylemanna/docker-bitcoind#79]
Data is not stored into `/bitcoin`. I ssh into the container and it is empty even while is downloading the blockchain.

**Comment by kalop** [comment]
The absolute path where the data is stored is: "/bitcoin/.bitcoin"

**Comment by kalop** [comment]
> Data is not stored into `/bitcoin`. I ssh into the container and it is empty even while is downloading the blockchain.

The absolute path where the data is stored is: "/bitcoin/.bitcoin"

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you
