### ISSUE TITLE
Docker images for ARM

### ISSUE THREAD

**Issue by trbouma** [kylemanna/docker-bitcoind#85]
HI - have you successfully built images for arm processors (raspberry pi) ? I have this working well on intel cpu but trying to get it working for the raspberry pi. Thanks

**Comment by kylemanna** [comment]
Should be resolved by #103

**Comment by 2flea** [comment]
I am a newbie to BTC nodes, I try to run your image in docker on a RPi4 with 64bit Raspbian OS (Linux raspberrypi 5.15.84-v8+ #1610 SMP PREEMPT Mon Dec 19 18:54:50 GMT 2022 aarch64 GNU/Linux). Whenever I try to run your docker image it comes back (starts and stops immediately) with error:
`exec /usr/local/bin/docker-entrypoint.sh: exec format error
`
I tried to run the additional lines from #103 but without success. 
Any suggestion here?
