### ISSUE TITLE
Write-up bittorrent seed node

### ISSUE THREAD

**Issue by kylemanna** [kylemanna/docker-bitcoind#9]
The kylemanna/bitcoin image has everything in it act as a bittorrent seed node.  Need to find time to write it up.

Thoughts:
* Separate running docker container (one container for bitcoind, one for aria2 seeder)
* Would clean-up old stale bootstrap file by relocating it and using it to seed
* Write-up howto and place in docs folder
* Add seeder.init script for those on Ubuntu VMs that want to seed

**Comment by hectorj** [comment]
See https://github.com/kylemanna/docker-bitcoind/issues/10#issuecomment-109705180

**Comment by Levino** [comment]
Please don't. This is bloating it up. Write a second docker image that expects a bitcoind container to be linked. If you were using env variables for setting rpc password and username the other container could even pull that from the linked container if I am not mistaken.

**Comment by kylemanna** [comment]
Alot has changed in 6 months.  No point in doing pointless work.
