### ISSUE TITLE
version 22.0

### ISSUE THREAD

**Issue by sirnicolas21** [kylemanna/docker-bitcoind#90]
https://github.com/bitcoin/bitcoin/commits/22.x
not that it blocks anyone from working with bitcoin but an update for the docker to v22 would be nice

**Comment by turcane** [comment]
Please update asap.

**Comment by kylemanna** [comment]
I will update it when an official binary is published and signed on the download page.

https://bitcoin.org/en/download

**Comment by turcane** [comment]
bitcoin.org was compromised a few days ago.
You should stick to the official github repository: https://github.com/bitcoin/bitcoin/releases
This leads to the download page: https://bitcoincore.org/bin/bitcoin-core-22.0/

**Comment by kylemanna** [comment]
Oops, I meant bitcoincore.org but was in a hurry.  I failed to noticed the new updates some time ago on bitcoincore due to the change in the version number and dropping the leading `0`.

**Comment by kylemanna** [comment]
Continue discussion and testing in #91
