### ISSUE TITLE
Bitcoin core 22

### ISSUE THREAD

**Issue by michal-podzimek** [kylemanna/docker-bitcoind#94]
Hello,
how can I upgrade Bitcoin core to version 22. I have latest version of Kylemanna and there is:
root@bitcoind:~# bitcoin-cli -version
Bitcoin Core RPC client version v0.21.1

Thank you.
Michal

**Comment by dasilvatek** [comment]
@michal-podzimek It was merged and updated last night, so you can pull the latest image now:
https://hub.docker.com/r/kylemanna/bitcoind/
