### ISSUE TITLE
Choose What Type of Node to Run

### ISSUE THREAD

**Issue by kalnun** [kylemanna/docker-bitcoind#97]
It would be really useful if we could decide to run a full node or lightweight node with something like:

```bash
NODETYPE:
0 = Full Node
1 = Lightweight Node
```

```docker
image: kylemanna/bitcoind
environment:
  - PRINTTOCONSOLE=1
  - NODETYPE=1
```

**Comment by kylemanna** [comment]
Should be able to pass them on the command line or use a config file. Not going to introduce more complexity here that'll just break later.
